package com.example.ffbclient.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.ffbclient.model.VoiceBean;

import com.example.ffbclient.db.VoiceBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig voiceBeanDaoConfig;

    private final VoiceBeanDao voiceBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        voiceBeanDaoConfig = daoConfigMap.get(VoiceBeanDao.class).clone();
        voiceBeanDaoConfig.initIdentityScope(type);

        voiceBeanDao = new VoiceBeanDao(voiceBeanDaoConfig, this);

        registerDao(VoiceBean.class, voiceBeanDao);
    }
    
    public void clear() {
        voiceBeanDaoConfig.clearIdentityScope();
    }

    public VoiceBeanDao getVoiceBeanDao() {
        return voiceBeanDao;
    }

}
